namespace Suran.DailyReport;

// 日报 HTML 模板：CSS 变量驱动 5 套主题，占位符由模块在生成时替换
public static class ReportTemplate
{
    public const string Html =
"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<style>
:root {
    --bg: #fdf6e3; --card: #fffdf7; --primary: #e6a23c; --accent: #b8860b;
    --text: #5b4636; --soft: #9c8a72; --line: #f0e2c8;
}
.theme-sakura { --bg:#fff0f5; --card:#fffafa; --primary:#ff8fab; --accent:#e75480; --text:#6d4356; --soft:#c494a6; --line:#ffd9e3; }
.theme-clover { --bg:#f0fff4; --card:#fafffa; --primary:#6abe83; --accent:#2e8b57; --text:#2f4f3a; --soft:#8aa894; --line:#d4ecd9; }
.theme-diamond { --bg:#2b2b2b; --card:#383838; --primary:#d4af37; --accent:#ffd700; --text:#f0f0f0; --soft:#9a9a8a; --line:#4a4a4a; }
.theme-sky { --bg:#e8f4fd; --card:#f7fcff; --primary:#5db8ee; --accent:#1e90ff; --text:#2f5b7c; --soft:#8fb4cc; --line:#d0e8fa; }
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    background: var(--bg); color: var(--text);
    font-family: "Microsoft YaHei", "PingFang SC", sans-serif;
    width: 720px; padding: 24px 20px;
}
.card {
    background: var(--card); border: 2px solid var(--line); border-radius: 16px;
    padding: 18px 20px; margin-bottom: 16px; box-shadow: 0 2px 8px rgba(0,0,0,.06);
}
.header { text-align: center; padding: 22px 20px 18px; }
.header .group-name { font-size: 26px; font-weight: 800; color: var(--accent); letter-spacing: 2px; }
.header .date-line { margin-top: 6px; font-size: 14px; color: var(--soft); }
.header .stamp { width: 64px; height: 64px; border-radius: 50%; margin: 0 auto 10px; border: 3px solid var(--primary); object-fit: cover; }
.stats { display: flex; justify-content: space-between; gap: 10px; }
.stat { flex: 1; text-align: center; }
.stat .num { font-size: 22px; font-weight: 800; color: var(--primary); }
.stat .label { font-size: 12px; color: var(--soft); margin-top: 4px; }
.section-title { font-size: 16px; font-weight: 800; color: var(--accent); margin-bottom: 10px; }
.topic { margin-bottom: 10px; padding-left: 12px; border-left: 4px solid var(--primary); }
.topic .t-name { font-size: 15px; font-weight: 700; }
.topic .t-sum { font-size: 12px; color: var(--soft); margin-top: 2px; line-height: 1.5; }
.user-row { display: flex; align-items: center; margin-bottom: 8px; }
.user-row .rank { width: 26px; font-weight: 800; color: var(--primary); }
.user-row img { width: 34px; height: 34px; border-radius: 50%; margin-right: 10px; object-fit: cover; }
.user-row .u-name { font-size: 14px; font-weight: 600; }
.user-row .u-count { margin-left: auto; font-size: 13px; color: var(--soft); }
.quote { background: var(--bg); border-radius: 10px; padding: 10px 12px; margin-bottom: 8px; }
.quote .q-text { font-size: 14px; font-weight: 600; line-height: 1.5; }
.quote .q-meta { font-size: 12px; color: var(--soft); margin-top: 4px; }
.comment { font-size: 14px; line-height: 1.7; }
.footer { text-align: center; font-size: 11px; color: var(--soft); margin-top: 4px; }
</style>
</head>
<body class="theme-__THEME__">
<div class="card header">
    <img class="stamp" src="__GROUP_AVATAR__">
    <div class="group-name">__GROUP_NAME__ 群聊日报</div>
    <div class="date-line">__DATE_RANGE__ · __THEME_NAME__</div>
</div>
<div class="card">
    <div class="stats">
        <div class="stat"><div class="num">__TOTAL__</div><div class="label">消息总数</div></div>
        <div class="stat"><div class="num">__PARTICIPANTS__</div><div class="label">参与人数</div></div>
        <div class="stat"><div class="num">__ACTIVE_RANGE__</div><div class="label">最活跃时段</div></div>
    </div>
</div>
<div class="card">
    <div class="section-title">🔥 热门话题</div>
    __TOPICS__
</div>
<div class="card">
    <div class="section-title">👤 活跃用户 TOP__TOPN__</div>
    __USERS__
</div>
<div class="card">
    <div class="section-title">💡 今日金句</div>
    __QUOTES__
</div>
<div class="card">
    <div class="section-title">🤖 __BOT_NAME__ 锐评</div>
    <div class="comment">__COMMENT__</div>
</div>
<div class="footer">Generated by Suran.DailyReport · 数据来自群聊记录</div>
</body>
</html>
""";
}
